### ISSUE TITLE
Hot to set colorscheme on windows?

### ISSUE THREAD

**Issue by r44083** [xaizek/vifm#7]
I download solarized-dark.vifm and put it into ```.\data\colors\``` then I added ```colorscheme solarized-dark``` into the vifmrc file, but colorscheme didn't change. Is it possible to setup colorscheme in windows without changing default colorset in link properties?

**Comment by xaizek** [comment]
That's quite confusing, but that directory is not used to look up color schemes. See output of
```
:echo $VIFM.'/colors/'
```
inside vifm to find out where you need to put colorschemes.

There should be no problem in making `data/colors` a global storage for colorschemes on Windows, I just didn't though of that while adding `/etc/vifm/colors` on Unix-like systems. So thanks for bringing this up, I'll add processing of `data/colors`.

P.S. [vifm/vifm](https://github.com/vifm/vifm) repository should be used for issues, this one is left mainly for experiments with integrations.

**Comment by xaizek** [comment]
Now that's embarrassing, but installation of help file and sample vifmrc, which were advertised to work on Windows since 0.8, didn't work until today... Thanks again, I find that issue while adding changes for this one.

If you want to use `data/colors` and don't mind using development version, you can grab [32-bit](http://builds.vifm.info/builds/vifm-w32-se-v0.8.2-367-g53bd46e6b01f.exe) or [64-bit](http://builds.vifm.info/builds/vifm-w64-se-v0.8.2-367-g53bd46e6b01f.exe) executable from CI.

By the way, `colors` directory should be where `vifmrc` file is, that's another way of finding it.
